### ISSUE TITLE
Unable to find caret in UWP listviews

### ISSUE THREAD

**Issue by trypsynth** [lukaszgo1/percentageChecker#3]
STR:
1. Open Unigram.
2. Open a chat.
3. Focus the chats list.
4. Press NVDA+Shift+P

I hear: Caret not found

**Comment by lukaszgo1** [comment]
As far as I know to be able to use Unigram you need to have Telegram account which, in turn, requires you to provide your phone number to Telegram, which I'm unwilling to do, so to debug this I would need to rely on additional info from you. Please paste the developer info for the list item in Unigram to this issue.

**Comment by trypsynth** [comment]
The main weird thing I notice is that the role is a checkbox, but when I tab to it, its most certainly a list. Maybe a list of checkboxes?
INFO - globalCommands.script_navigatorObject_devInfo (14:14:34.988) - MainThread (5536):
Developer info for navigator object:
name: 'TT?, Sent at \u200e1\u200e:\u200e34\u200e \u200ePM. Not seen.'
role: Role.CHECKBOX
roleText: None
states: State.FOCUSABLE, State.CHECKABLE, State.FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x075C6F70>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=540, top=952, width=1380, height=34)
value: None
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
appModule: <'appModuleHandler' (appName 'unigram', process ID 6856) at address 10a10b0>
appModule.productName: '38833FF26BA1D.UnigramPreview'
appModule.productVersion: '8.8.7438.0'
appModule.helperLocalBindingHandle: c_long(99402952)
windowHandle: 1507772
windowClassName: 'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: 1409286144
extendedWindowStyle: 2621440
windowThreadID: 9900
windowText: 'Unigram'
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x7d5f120 at 772ba80>
UIA automationID: 
UIA frameworkID: XAML
UIA runtimeID: (42, 1507772, 4, 208)
UIA providerDescription: [pid:6856,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)]
UIA className: CheckBox
UIA patterns available: ScrollItemPattern, TogglePattern, LegacyIAccessiblePattern

**Comment by lukaszgo1** [comment]
1. After focusing the list item and pressing NVDA+_tab what role is reported by NVDA - list item or checkbox?
2. Can NVDA report position info for these list items?

**Comment by trypsynth** [comment]
Checkbox is reported, but NVDA does give me position information.

**Comment by lukaszgo1** [comment]
Can you tell why these lists in Unigram are checkboxes instead of normal list items? In the issue title you mentioned UWP lists, but this affects only Unigram - right?

**Comment by trypsynth** [comment]
Yeah, this is weird actually, even the chats list in Unigram works, just not the messages list. They're checkboxes because you check them for telegram reactions, I think.

**Comment by trypsynth** [comment]
Parts of the Unigram list work, it looks like the actual messages aren't list items, but the time headings are. Weird... but I'll close this, at least for now.
